### ISSUE TITLE
如果一段文字全部是夹注，则夹注模块不起作用

### ISSUE THREAD

**Issue by walkthetalk** [Fusyong/jiazhu#3]
不但没有排成两行，而且超出文字区域有边界。

![image](https://github.com/Fusyong/jiazhu/assets/980420/1730840c-41ab-4c67-b349-222a7f6fa702)

**Comment by walkthetalk** [comment]
好像如果整段都是夹注，则 hbox 会失效，即节点清单里没有 带 attr 2 222 的 hlist，看起来像是 hbox 被吸收了。

**Comment by Fusyong** [comment]
> 好像如果整段都是夹注，则 hbox 会失效，即节点清单里没有 带 attr 2 222 的 hlist，看起来像是 hbox 被吸收了。

您说得对，hbox被吸收了。我对tex的解释机制还不是太了解，也许应该换一种占位方式。

目前请用`~\kern-0.25em\jiazh{夹注内容}`或`\jiazh{夹注内容}~\kern-0.25em`这样的办法来临时应付一下。

**Comment by Fusyong** [comment]
> 目前请用`~\kern-0.25em\jiazh{夹注内容}`或`\jiazh{夹注内容}~\kern-0.25em`这样的办法来临时应付一下。

[temporary hacking for only one jiazhu for an entire paragraph](https://github.com/Fusyong/jiazhu/commit/e67b0e1604f5fe74c303a39678d7f0421e22d1fd)
