### ISSUE TITLE
过长的夹注需要优化

### ISSUE THREAD

**Issue by walkthetalk** [Fusyong/jiazhu#8]
如果夹注过长，会使得夹注占据了大部分空间，其长度固定下来后，可能导致剩余空间进行标点压缩排版时超出边界。
根本原因应该是夹注无法与非夹注一起参与glue的缩放，而夹注长度一旦固定下来，如果剩余空间过小会导致排版困难。
![overflow](https://github.com/Fusyong/jiazhu/assets/980420/5409a247-0589-4a78-8727-cbd243ca2e56)

**Comment by walkthetalk** [comment]
微软的word中名字叫双行合一，感觉我们也可以借鉴一下，划分成两行后，将第一行夹注打散和剩余部分一起 hpack进行缩放重排，然后找到打散后的夹注左右边界，将第二行的夹注按这个宽度进行重排，尤其是夹注比较长时，这种方式应该会更好一些。
可以设置一些阈值，比如超过多少个字符，或者超过正行宽度的某个百分比后，就使用这种方式对夹注进行重排。

**Comment by Fusyong** [comment]
这个问题可能是官方的标点禁则对冒号的分类错误造成的。你把冒号换一下或删除，大概就能正常断行。目前可以自行修改官方的标点禁则（_稍后我把我的更改贴出来_）。
这个问题我提交过一次，但是当次提交的问题过多、过杂，导致他们没有好好对待，以后在单独提一次

**Comment by Fusyong** [comment]
我的更改见[source-reviewed](https://github.com/Fusyong/context-source-studying/tree/master/source-reviewed)：
- char-scr.lua 
- scrp-cjk.lua
